// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var count, currentStatement, onMeClick, onNotMeClick, onReloadClick, onShareClick, render, statements, watches, winner;
    statements = ["My purse: I'm willing to invest in it to get exactly what I want.", "I don't care what other people think of me.", "I'm interested in what material my home curtains are made of", "I always think that successful people should show their success.", "It's not what you do, it's how you do it."];
    watches = [
      {
        name: "Michael Kors bags",
        products: [
          {
            productname: "Hamilton Center Stripe Studded LG NS Tote",
            image: "https://imaging.stockmann.com/web/112/382/056/F_86de85e51416ae8a105bdbe60b7c873773f00c64/112382056_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/michael-michael-kors-hamilton-center-stripe-studded-lg-ns-tote-nahkalaukku--11301/119713?itemId=826353"
          }
        ],
        share: "According to AskMeFive.co test, I'm not afraid to show that I've made it in life. What your taste tells about you?",
        result: [""],
        points: [10, 10, -2, 2, 1],
        total: 0
      }, {
        name: "Ralph Lauren",
        products: [
          {
            productname: "Convertible Tote",
            image: "https://imaging.stockmann.com/web/115/607/194/F_c361a02888a964e773457c74d982c2ab076db3db/115607194_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/lauren-ralph-lauren-convertible-tote-nahkalaukku--11301/119713?itemId=811608"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, 10, -1, -2, -2],
        total: 0
      }, {
        name: "Aigner",
        products: [
          {
            productname: "Quadriga M",
            image: "https://imaging.stockmann.com/web/118/206/158/F_5770422c5340724176d7d2c237c9375886106c3b/118206158_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/aigner-quadriga-m-nahkalaukku--11301/119713?itemId=896531"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, 10, 2, 0, -3],
        total: 0
      }, {
        name: "Furla",
        products: [
          {
            productname: "Cortina L",
            image: "https://imaging.stockmann.com/web/118/875/859/F_6896dd30f3d34f7338ce69b655928c07c416a172/118875859_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/cortina-l-nahkalaukku-926410--11301/119713?itemId=926411"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, 10, -1, 1, 2],
        total: 0
      }, {
        name: "Furla",
        products: [
          {
            productname: "New Piper Lux L",
            image: "https://imaging.stockmann.com/web/118/879/710/F_7cb9eafd79008cb3b8f83f4336bf5b6278f75480/118879710_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/new-piper-lux-l-nahkalaukku--11301/119713?itemId=926534"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, -10, -2, 2, 1],
        total: 0
      }, {
        name: "Ralph Lauren",
        products: [
          {
            productname: "Newbury Belted Satchel",
            image: "https://imaging.stockmann.com/web/118/956/350/F_4aedff9373a34bc6bf21cdf56653b41d15392efb/118956350_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/lauren-ralph-lauren-newbury-belted-satchel-nahkalaukku--11301/119713?itemId=931685"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, -10, -1, -2, -2],
        total: 0
      }, {
        name: "Aigner",
        products: [
          {
            productname: "Aigner",
            image: "https://imaging.stockmann.com/web/020/203/032/324/5/F_0ff7aa3a6c80dfa12ab7a501525e31926d783d72/0202030323245_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/aigner-nahkalaukku-725292--11301/119713?itemId=725293"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, -10, 2, 0, -3],
        total: 0
      }, {
        name: "Michael Kors",
        products: [
          {
            productname: "Hamilton LG Traveler",
            image: "https://imaging.stockmann.com/web/119/003/244/F_4ed5bbd0397dee8686ea4e7900eb1143f0cf5c76/119003244_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/michael-michael-kors-hamilton-lg-traveler-nahkalaukku?itemId=934803"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [10, -10, -1, 1, 2],
        total: 0
      }, {
        name: "Global Accessories",
        products: [
          {
            productname: "Global Accessories",
            image: "https://imaging.stockmann.com/web/111/030/958/F_04b9b6bcb7f1e83a48700ea5afeb5aa12f466aab/111030958_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/global-accessories-nahkalaukku-784692--11301/119713?itemId=784694"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, 10, -2, 2, 1],
        total: 0
      }, {
        name: "Armani Jeans",
        products: [
          {
            productname: "Armani Jeans",
            image: "https://imaging.stockmann.com/web/112/536/145/F_f11e2ae404003b1fed8e39cbee277e43f09d2567/112536145_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/armani-jeans-laukku-876584--11301/119713?itemId=876585"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, 10, -1, -2, -2],
        total: 0
      }, {
        name: "Marimekko",
        products: [
          {
            productname: "Marimekko",
            image: "https://imaging.stockmann.com/web/118/461/083/F_20a27ef109585a3d8e9ecc96dcf2cc31930059d5/118461083_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/marimekko-mini-weekender-laukku-907398--11301/119713?itemId=907399"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, 10, 2, 0, -3],
        total: 0
      }, {
        name: "Ralph Lauren",
        products: [
          {
            productname: "Denim & Supply",
            image: "https://imaging.stockmann.com/web/115/682/146/F_ecea608c6b2fbc3b124c327bf2065ca00b20b05d/115682146_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/denim-supply-ralph-lauren-kanvaslaukku--11301/119713?itemId=825307"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, 10, -1, 1, 2],
        total: 0
      }, {
        name: "Ralph Lauren",
        products: [
          {
            productname: "Novelty N/S Tote",
            image: "https://imaging.stockmann.com/web/020/202/903/891/4/F_5666db0c144a977f8fa8142057086090f3d06d74/0202029038914_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/lauren-ralph-lauren-novelty-n-s-tote-laukku--11301/119713?itemId=760294"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, -10, -2, 2, 1],
        total: 0
      }, {
        name: "Armani Jeans",
        products: [
          {
            productname: "Armani Jeans",
            image: "https://imaging.stockmann.com/web/112/526/726/F_d9dea92c444c1344c136bfe24fefb7313625c6cf/112526726_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/armani-jeans-laukku-876576--11301/119713?itemId=876577"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, -10, -1, -2, -2],
        total: 0
      }, {
        name: "Marimekko",
        products: [
          {
            productname: "Olkalaukku",
            image: "https://imaging.stockmann.com/web/020/200/812/684/7/F_6134024a304c730aa8bdbe809bdb80e079cfbf1e/0202008126847_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/marimekko-olkalaukku--11301/119713?itemId=671734"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, -10, 2, 0, -3],
        total: 0
      }, {
        name: "Global Accessories",
        products: [
          {
            productname: "Global Accessories",
            image: "https://imaging.stockmann.com/web/111/022/311/F_7f3d44f9c4c6b66df5d1c52d18fbd826743976e6/111022311_1.jpg?width=769&height=1026",
            link: "https://stockmann.com/fi/naiset/asusteet/laukut-ja-lompakot/laukut/global-accessories-nahkalaukku-784763--11301/119713?itemId=784765"
          }
        ],
        share: "According to AskMeFive.co test, I'm know my preferences. What your taste tells about you?",
        result: [""],
        points: [-10, -10, 2, 0, -3],
        total: 0
      }
    ];
    onMeClick = function() {
      count(1);
      return render();
    };
    onNotMeClick = function() {
      count(-1);
      return render();
    };
    onShareClick = function() {
      return FB.ui({
        method: "feed",
        link: "http://whichbrandisme.com",
        name: 'Find out which watch brand is most like you',
        caption: 'Take the WhichBrandIsMe watch test to find out which watch brand fits your personality and style.',
        description: winner.share,
        picture: 'https://imaging.stockmann.com' + winner.products[0].affiliateid
      });
    };
    onReloadClick = function() {
      return location.reload(true);
    };
    currentStatement = 0;
    winner = {};
    count = function(sign) {
      if (sign == null) {
        sign = 1;
      }
      _(watches).each(function(w) {
        return w.total += w.points[currentStatement] * sign;
      });
      return currentStatement += 1;
    };
    render = function() {
      var resultHtml;
      if (currentStatement < statements.length) {
        if ($("#container").hasClass("hide")) {
          $("#container").fadeIn(function() {
            return $(this).removeClass("hide");
          });
        }
        $("#js-content").html(Handlebars.compile($("#step-template").html())({
          statement: statements[currentStatement]
        }));
        return $("#js-progress > .meter").animate({
          width: 100 * currentStatement / statements.length + "%"
        });
      } else {
        winner = _(watches).sortBy("total").reverse()[0];
        resultHtml = Handlebars.compile($("#result-template").html())(winner);
        return $("#js-progress > .meter").animate({
          width: "100%"
        }, {
          complete: function() {
            return $("#container").html(resultHtml);
          }
        });
      }
    };
    $(document).on("click", "#js-me", onMeClick).on("click", "#js-notme", onNotMeClick).on("click", "#js-share", onShareClick).on("click", "#js-reload", onReloadClick);
    return render();
  });

}).call(this);
